name: Desplegar OpenAPI en WSO2

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Código
    - name: Checkout
      uses: actions/checkout@v3

    # 2. apictl
    - name: Instalar apictl 4.3.3
      run: |
        DOWNLOAD="apictl-4.3.3-linux-amd64.tar.gz"
        curl -Lf -o "$DOWNLOAD" \
          https://github.com/wso2/product-apim-tooling/releases/download/v4.3.3/"$DOWNLOAD"
        tar -xzf "$DOWNLOAD"
        sudo install -m 755 apictl/apictl /usr/local/bin/apictl
        apictl version

    # 3. Entorno ngrok
    - name: Añadir entorno WSO2 (ngrok)
      env:
        APIM_ENDPOINT:       ${{ secrets.APIM_ENDPOINT }}
        APIM_TOKEN_ENDPOINT: ${{ secrets.APIM_TOKEN_ENDPOINT }}
      run: |
        apictl add env dev-env \
          --apim  "$APIM_ENDPOINT" \
          --token "$APIM_TOKEN_ENDPOINT" \
          --insecure

    # 4. Login
    - name: Iniciar sesión en WSO2 APIM
      env:
        APIM_USER: ${{ secrets.APIM_USER }}
        APIM_PASS: ${{ secrets.APIM_PASS }}
      run: |
        apictl login dev-env -u "$APIM_USER" -p "$APIM_PASS" -k

    # 5. Despliegue: usar --oas
    - name: Desplegar definiciones OpenAPI
      run: |
        echo "Buscando archivos api.yaml..."
        shopt -s globstar nullglob
        for oas in apis/**/api.yaml; do
          echo "Importando $oas"
          apictl import api \
            --oas "$oas" \
            -e dev-env \
            --update \
            --insecure \
            --verbose
        done
        echo "Despliegue completado"

    # 6. (Opcional) Listar APIs
    - name: Listar APIs desplegadas
      run: apictl list apis -e dev-env -k