name: Desplegar OpenAPI en WSO2

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v3

    - name: Instalar apictl (amd64 v4.3.3)
      run: |
        DOWNLOAD_FILE="apictl-4.3.3-linux-amd64.tar.gz"
        APIC_FOLDER="apictl"
        curl -L -f -o "$DOWNLOAD_FILE" \
          https://github.com/wso2/product-apim-tooling/releases/download/v4.3.3/"$DOWNLOAD_FILE"
        tar -xzf "$DOWNLOAD_FILE"
        sudo install -m 755 "$APIC_FOLDER"/apictl /usr/local/bin/apictl
        apictl version

    - name: Añadir entorno WSO2 (ngrok)
      env:
        APIM_ENDPOINT:       ${{ secrets.APIM_ENDPOINT }}
        APIM_TOKEN_ENDPOINT: ${{ secrets.APIM_TOKEN_ENDPOINT }}
      run: |
        apictl add env dev-env \
          --apim  "$APIM_ENDPOINT" \
          --token "$APIM_TOKEN_ENDPOINT" \
          --insecure
        echo "Entorno dev-env apuntando a $APIM_ENDPOINT"

    - name: Iniciar sesión en WSO2 APIM
      env:
        APIM_ENDPOINT:       ${{ secrets.APIM_ENDPOINT }}
        APIM_USER:           ${{ secrets.APIM_USER }}
        APIM_PASS:           ${{ secrets.APIM_PASS }}
      run: |
        apictl login dev-env \
          -u "$APIM_USER" -p "$APIM_PASS" -k
        echo "Sesión iniciada contra $APIM_ENDPOINT"

    - name: Desplegar todas las definiciones OpenAPI
      env:
        APIM_ENDPOINT: ${{ secrets.APIM_ENDPOINT }}
      run: |
        echo "Buscando definiciones OpenAPI para desplegar..."
        for dir in apis/*/*; do
          if [ -d "$dir" ] && [ -f "$dir/api.yaml" ]; then
            echo "Importando API desde $dir ..."
            apictl import-api -f "$dir" -e dev-env --update --insecure
          fi
        done
        echo "Despliegue completado."