name: Deploy OpenAPI to WSO2

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install apictl (ARM64)
      run: |
        wget https://github.com/wso2/product-apim-tooling/releases/download/v4.3.3/apictl-4.3.3-linux-arm64.tar.gz -O apictl.tar.gz
        tar -xzf apictl.tar.gz
        chmod +x apictl-4.3.3-linux-arm64/apictl
        sudo mv apictl-4.3.3-linux-arm64/apictl /usr/local/bin/apictl

    - name: Add WSO2 Environment
      run: |
        apictl add-env -e dev-env \
          --apim https://localhost:9443 \
          --token https://localhost:9443/oauth2/token \
          --insecure

    - name: Login to WSO2 APIM
      run: apictl login dev-env -u ${{ secrets.APIM_USER }} -p ${{ secrets.APIM_PASS }} --insecure

    - name: Deploy all OpenAPI definitions
      run: |
        for dir in apis/*/*; do
          if [ -f "$dir/api.yaml" ]; then
            echo "Importando $dir/api.yaml"
            apictl import-api -f "$dir" -e dev-env --update --insecure
          fi
        done