# Contenido de tu archivo scoring.yml (o como se llame)
name: Scoring Workflow

on:
  workflow_dispatch: # Permite que este workflow sea disparado manualmente o por API
    inputs: # Opcional: si quieres pasar datos al workflow de scoring
      triggering_workflow_ref:
        description: 'Referencia (rama/tag) del workflow que lo disparó'
        required: false
      # Puedes añadir más inputs aquí

jobs:
  execute_scoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.triggering_workflow_ref || github.ref }} # Usa el ref pasado o el del propio workflow

      - name: Mostrar información del trigger (opcional)
        run: |
          echo "Workflow de Scoring disparado."
          echo "Referencia: ${{ github.event.inputs.triggering_workflow_ref || github.ref }}"
          # Accede a otros inputs con: ${{ github.event.inputs.nombre_del_input }}

      - name: Ejecutar lógica de scoring
        run: |
          echo "Ejecutando el proceso de scoring..."
          # Aquí irían tus comandos de scoring