# .github/workflows/scoring_action.yml
name: API Scoring

on:
  workflow_run:
    workflows: ["Importar"]        
    types:
      - completed

jobs:
  run-scoring:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1) Código fuente de tu repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Clonar el motor de scoring
      - name: Clone scoring engine
        run: |
          git clone --depth 1 https://github.com/rgranadosd/api-scoring-engine.git scoring_engine

      # 3) Añadir wrapper solo si falta docker-compose
      - name: Habilitar docker-compose (wrapper para Compose v2)
        run: |
          if ! command -v docker-compose &>/dev/null; then
            echo '#!/usr/bin/env bash'      | sudo tee  /usr/local/bin/docker-compose
            echo 'exec docker compose "$@"' | sudo tee -a /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

      # 4) Arrancar el contenedor de scoring (sin cambiar tu comando)
      - name: Start scoring engine (Docker Compose)
        working-directory: scoring_engine
        run: |
          docker-compose up --build -d
          echo "⏳ Esperando a que el servicio responda en http://localhost:8088 ..."
          for i in {1..30}; do
            if curl -s http://localhost:8088/ | grep -qiE "api|swagger|health"; then
              echo "Scoring engine listo"; break; fi
            sleep 5
          done

      # 5) Llamada a la API de scoring (igual que antes)
      - name: Call scoring API
        id: score
        run: |
          curl -s -X POST -F "file=@openapi-rest.yml;type=text/yaml" \
               http://localhost:8088/apifirst/v1/apis/score-file \
               -o score.json
          GRADE=$(jq -r '.overallGrade // .grade // empty' score.json)
          echo "grade=${GRADE}" >> "$GITHUB_OUTPUT"
          echo "#### Resultado bruto" >> "$GITHUB_STEP_SUMMARY"
          cat score.json >> "$GITHUB_STEP_SUMMARY"

      # 6) Publicar el artefacto con la nota
      - name: Upload score
        uses: actions/upload-artifact@v4
        with:
          name: api-score
          path: score.json

      # 7) Apagar y limpiar el contenedor, pase lo que pase
      - name: Tear-down scoring engine
        if: always()
        working-directory: scoring_engine
        run: docker-compose down