name: API Scoring

on:
  workflow_run:
    workflows: ["Importar"]
    types:
      - completed

jobs:
  run-scoring:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone scoring engine
        run: |
          git clone --depth 1 https://github.com/rgranadosd/api-scoring-engine.git scoring_engine
