name: API Scoring

on:
  workflow_run:
    workflows: ["Importar"]          # ← Debe coincidir EXACTAMENTE con el name: del flujo padre
    types: [completed]

jobs:
  run-scoring:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout del repositorio
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2) Clonar el motor de scoring
    - name: Clone scoring engine
      run: git clone --depth 1 https://github.com/rgranadosd/api-scoring-engine.git scoring_engine

    # 3) Crear alias docker-compose si el runner sólo trae Compose v2
    - name: Enable docker-compose alias if needed
      run: |
        if ! command -v docker-compose &>/dev/null; then
          printf '#!/usr/bin/env bash\nexec docker compose "$@"\n' \
            | sudo tee /usr/local/bin/docker-compose >/dev/null
          sudo chmod +x /usr/local/bin/docker-compose
        fi

    # 4) Arrancar contenedor y esperar a que /health devuelva 200 OK
    - name: Start scoring engine
      working-directory: scoring_engine
      run: |
        docker-compose up --build -d
        echo "⏳ Waiting for /health 200..."
        for i in {1..30}; do
          curl -sf http://localhost:8088/health >/dev/null && { echo "✅ Ready"; break; }
          sleep 5
          [[ $i -eq 30 ]] && { echo "::error::Timeout"; docker-compose logs; exit 1; }
        done

    # 5) Localizar todas las especificaciones apis/**/api.yaml
    - name: Find api.yaml
      id: specs
      run: |
        mapfile -t SPEC_FILES < <(git ls-files 'apis/**/api.yaml')
        [ ${#SPEC_FILES[@]} -eq 0 ] && { echo "::error::No api.yaml found"; exit 1; }
        { echo 'specs<<EOF'; printf '%s\n' "${SPEC_FILES[@]}"; echo 'EOF'; } >> "$GITHUB_OUTPUT"

    # 6) Calcular scoring y generar Job Summary coloreado
    - name: Run scoring & build summary
      run: |
        mapfile -t SPECS <<<"${{ steps.specs.outputs.specs }}"
        mkdir -p scores

        # Cabecera del resumen
        {
          echo "## Resultados de calidad de las APIs"
          echo
          echo "| API | Módulo | Nota |"
          echo "|-----|--------|------|"
        } >> "$GITHUB_STEP_SUMMARY"

        # Función para colorear celdas
        color () {
          [[ "$1" =~ ^([A]|B($|\+)) ]] \
            && printf "<span style='color:#22863a;font-weight:bold;'>%s</span>" "$1" \
            || printf "<span style='color:#d91e18;font-weight:bold;'>%s</span>" "$1"
        }

        for spec in "${SPECS[@]}"; do
          api=$(basename "$(dirname "$(dirname "$spec")")")
          ver=$(basename "$(dirname "$spec")")
          out="scores/${api}_${ver}.json"

          echo "⏩ Scoring $spec → $out"
          curl --fail -s \
            -X POST \
            -F "file=@${spec};type=text/yaml" \
            -F "apiProtocol=REST" \
            http://localhost:8088/apifirst/v1/apis/score-file \
            -o "$out"

          # ─── Fila Overall ───
          overall=$(jq -r '.overallGrade // .grade // "?"' "$out")
          echo "| ${api} ${ver} | **Overall** | $(color "$overall") |" >> "$GITHUB_STEP_SUMMARY"

          # ─── Recorrer .modules (array u objeto) ───
          jq -r '
            def pairs_from_array:
              map("\(.name // .module // .id)\t\(.grade // .score // .value // .rating // \"?\")");
            def pairs_from_object:
              to_entries | map("\(.key)\t\(.value)");

            (.modules // {}) as $m
            |  if ($m|type) == "array"  then $m | pairs_from_array[]
               elif ($m|type) == "object" then $m | pairs_from_object[]
               else empty end
          ' "$out" | while IFS=$'\t' read -r mod grade; do
              echo "| ${api} ${ver} | ${mod} | $(color "$grade") |" >> "$GITHUB_STEP_SUMMARY"
          done
        done

    # 7) Subir todos los JSON como artefacto
    - name: Upload scores
      uses: actions/upload-artifact@v4
      with:
        name: api-scores
        path: scores/

    # 8) Apagar y limpiar el contenedor (siempre)
    - name: Tear-down
      if: always()
      working-directory: scoring_engine
      run: docker-compose down